package definitions

// Instruction reference for 8086 CPU (https://edge.edx.org/c4x/BITSPilani/EEE231/asset/8086_family_Users_Manual_1_.pdf | page 161(pdf))
// [opcode|d|m] [mod|reg|r/m] [displacement-low] [displacement-high] [data] [data if w =1]
//    6    1 1    2   3   3
// The intel x86 processors use Little Endian, so the low byte comes first

const (
	INSTRUCTION_REFERENCE = "https://edge.edx.org/c4x/BITSPilani/EEE231/asset/8086_family_Users_Manual_1_.pdf"

	MOD          = "Mode field."
	REG          = "Register field."
	R_M          = "Register/Memory field."
	S_FIELD      = "Sign extension "
	W_FIELD      = "Size - byte/word"
	D_FIELD      = "Source or destination is specified in the 'REG' field"
	Z_FIELD      = "Loop while zero flag (ZF) is 0 or !0"
	V_FIELD      = "Shift/rotate count"
	SR           = "Segment register code: 00=ES, 01=CS, 10=SS, 11=DS."
	FLAGS        = "Single-bit instruction fields."
	DATA_8       = "8-bit immediate constant."
	DATA_SX      = "8-bit immediate value that is automatically sign-extended to 16-bits before use."
	DATA_LO      = "Low-order byte of 16-bit immediate constant."
	DATA_HI      = "High-order byte of 16-bit immediate constant."
	DISP_LO      = "Low-order byte of optional 8- or 16-bit unsigned displacement; MOD indicates if present."
	DISP_HI      = "High-order byte of optional 16-bit unsigned displacement; MOD indicates if present."
	IP_LO        = "Low-order byte of new IP value."
	IP_HI        = "High-order byte of new IP value."
	CS_LO        = "Low-order byte of new CS value."
	CS_HI        = "High-order byte of new CS value."
	IP_INC8      = "8-bit signed increment to instruction pointer."
	IP_INC_LO    = "Low-order byte of signed 16-bit instruction pointer increment."
	IP_INC_HI    = "High-order byte of signed 16-bit instruction pointer increment."
	ADDRL_O      = "Low-order byte of direct address (offset) of memory operand; EA not calculated."
	ADDR_HI      = "High-order byte of direct address (offset) of memory operand; EA not calculated."
	REG8         = "8-bit general register operand."
	REG16        = "16-bit general register operand."
	MEM8         = "8-bit memory operand (any addressing mode)."
	MEM16        = "16-bit memory operand (any addressing mode)."
	IMMED8       = "8-bit immediate operand."
	IMMED16      = "16-bit immediate operand."
	SEGREG       = "Segment register operand."
	DEST_STR     = "Byte string addressed by DI."
	SRC_STR8     = "Byte string addressed by SI."
	DEST_STR16   = "Word string addressed by DI."
	SRC_STR16    = "Word string addressed by SI."
	SHORT_LABEL  = "Label within ±127 bytes of instruction."
	NEAR_PROC    = "Procedure in current code segment."
	FAR_PROC     = "Procedure in another code segment."
	NEAR_LABEL   = "Label in current code segment but farther than -128 to +127 bytes from instruction."
	FAR_LABEL    = "Label in another code segment."
	SOURCE_TABLE = "XLAT translation table addressed by BX."
	OPCODE       = "ESC opcode operand."
	SOURCE       = "ESC register or memory operand."
)
